#' Error free data for all examples.
#'
#' A dataset generated by the rotation of a bivariate normal density, the method
#' applied to get this dataset is described on Wentzell, P. D., and S. Hou.
#' "Exploratory data analysis with noisy measurements."
#' Journal of Chemometrics 26.6 (2012): 264-281.
#'
#' @format A matrix with 300 rows and 20 columns
#' @references Wentzell, P. D., and S. Hou.
#' "Exploratory data analysis with noisy measurements."
#' Journal of Chemometrics 26.6 (2012): 264-281.
#'
"data_clean"
